Feature/tsw 003 order preview
Kasperone/tees_store_web_app pull request #1
Opened 2022-07-26 14:13 UTC by Kasperone

2022-07-26 21:45 UTC, entrop- requested changes

2022-07-26 21:45 UTC, entrop- commented on src/components/ActionButton.vue
> +    @apply h-[60px] rounded-[10px];
w remach lepiej niż w px ze względu na rwd, to nie musi być pixel perfect a remy się lepiej układają dla rwd

2022-07-26 21:45 UTC, entrop- commented on src/components/OrderPreview.vue
> +    <title-component class="pt-6 pb-5" text="Podgląd zamówienia" />
translacje do wszytkich stringów

2022-07-26 21:45 UTC, entrop- commented on src/components/OrderPreview.vue
> +    <title-component class="py-5" type="third" text="Kod Rabatowy :" />
jeśli nie jesteś francuzem to nie ma spacji przed znakami interpunkcyjnymi :D

2022-07-26 21:45 UTC, entrop- commented on src/components/OrderPreview.vue
> +      <div class="font-medium text-[20px] text-gray-800">0.00zł</div>
do walut tak samo działa i18n ($n), prosze używać

2022-07-26 21:45 UTC, entrop- commented on src/components/OrderPreview.vue
> +import ActionButton from "./ActionButton.vue";
sciezki zawsze absolutne od katalogu domowego (@)

2022-07-26 21:45 UTC, entrop- commented on src/components/TitleComponent.vue
> +  /* use for: Podgląd zamówienia */
jak już piszesz komcie to zdecyduj się na jeden język. nie wierzę też, że wejdziesz tutaj i będziesz edytował ten komentarz za każdym razem gdy użyjesz gdzieś komponentu, więc tak ogólnie to jest zbędny

2022-07-27 06:27 UTC, Sigwar commented on src/components/OrderPreview.vue
> +    <title-component class="pt-6 pb-5" text="Podgląd zamówienia" />
1. nazwa komponentu <c-title>
2. Jeżeli jest powyżej dwóch atrybutów to każdy do nowej linijki poza pierwszy
3. Jeżeli tag / komponent zawiera więcej niż jedną linijkę to po nim dajemy enter

2022-07-27 06:37 UTC, Sigwar commented on src/components/ActionButton.vue
> +      required: false,
required z defaulto jest ustawiony na false

2022-07-27 06:37 UTC, Sigwar commented on src/components/ActionButton.vue
> +  computed: {
Proszę użyj composition API

2022-07-27 06:39 UTC, Sigwar commented on src/components/OrderPreview.vue
> +      <button
pierwszy atrybut w jeden linijce razem z tagiem, jeżeli jest więcej niż jeden atrybut to każdy następny leci do nowego wiersza. Jeżeli tag / kompent jest wielo-linijkowy to dajemy enter po nim

2022-07-27 06:39 UTC, Sigwar commented on src/components/OrderPreview.vue
> +      >
znam ">" nie dajemy w nowej linijce, jest to mniej czytelne

2022-07-27 06:40 UTC, Sigwar commented on src/components/OrderPreview.vue
> +    <div class="flex flex-row justify-between pt-[50px]">
Zaczynasz nową "sekcje" enter przez tym div'em dla lepszej czytelności

2022-07-27 06:40 UTC, Sigwar commented on src/components/OrderPreview.vue
> +    <div class="flex flex-row justify-between mt-5">
jw

2022-07-27 06:41 UTC, Sigwar commented on src/components/OrderPreview.vue
> +  name: "OrderPreview",
Jeżeli jest to komponent to nazwa powinna być cOrderPreview -> c od component
Jeżeli jest to widok to nazwa powinna być vOrderPreview -> v od view

2022-07-27 06:41 UTC, Sigwar commented on src/views/HomeView.vue
> +  <order-preview />
Tag powinien mieć nazwę z przedrostkiem c lub v

2022-07-27 06:42 UTC, Sigwar commented on src/views/HomeView.vue
> +<script setup>
nie używamy <script setup> dla ujednolicenia projektu usuń setup z tagu script

2022-07-27 06:43 UTC, Sigwar commented on src/components/OrderPreview.vue
>        <input class="w-[270px] h-[59px] mr-[26px] bg-gray-300" type="text" />
atrybut type do nowej linijki, po zamknięciu tagu input enter dla lepszej czytelności

2022-07-27 06:43 UTC, Sigwar commented on src/components/TitleComponent.vue
> +  computed: {
Używamy composition API

2022-07-27 06:44 UTC, Sigwar commented on src/components/TitleComponent.vue
> +      required: false,
Required defaultowo jest ustawiony na false, więc nie musisz zapisywać 'required: false'

2022-07-27 07:07 UTC, Sigwar commented on src/views/HomeView.vue
> +  name: "HomeView",
zmień nazwę na vHome

2022-07-27 07:07 UTC, Sigwar commented on src/views/HomeView.vue
> +  <order-preview />
jeżeli to komponent to wtedy nazwa c-order-preview

2022-07-27 13:25 UTC, Kasperone commented on src/components/ActionButton.vue
> +    @apply h-[60px] rounded-[10px];
ok ogarnięte,

2022-07-27 13:26 UTC, Kasperone commented on src/components/OrderPreview.vue
> +    <title-component class="pt-6 pb-5" text="Podgląd zamówienia" />
translacje jeszcze w praniu,
1, 2, 3, ogarnięte

2022-07-27 13:27 UTC, Kasperone commented on src/components/OrderPreview.vue
> +    <title-component class="py-5" type="third" text="Kod Rabatowy :" />
:) poprawione

2022-07-27 13:31 UTC, Kasperone commented on src/components/OrderPreview.vue
> +      <div class="font-medium text-[20px] text-gray-800">0.00zł</div>
ok

2022-07-27 13:31 UTC, Kasperone commented on src/components/OrderPreview.vue
> +import ActionButton from "./ActionButton.vue";
ogarnięte

2022-07-27 13:33 UTC, Kasperone commented on src/components/TitleComponent.vue
> +  /* use for: Podgląd zamówienia */
ok to z rozpędu dwa języki. zapisałem sobie na następny dzień, już usunięte

2022-07-27 13:34 UTC, Kasperone commented on src/components/ActionButton.vue
> +      required: false,
usunięte

2022-07-27 13:35 UTC, Kasperone commented on src/components/OrderPreview.vue
> +      <button
ogarnięte

2022-07-27 13:35 UTC, Kasperone commented on src/components/OrderPreview.vue
> +      >
ogarnięte

2022-07-27 13:35 UTC, Kasperone commented on src/components/OrderPreview.vue
> +    <div class="flex flex-row justify-between pt-[50px]">
ok

2022-07-27 13:35 UTC, Kasperone commented on src/components/OrderPreview.vue
> +    <div class="flex flex-row justify-between mt-5">
ok

2022-07-27 13:35 UTC, Kasperone commented on src/components/OrderPreview.vue
> +  name: "OrderPreview",
ogarnięte

2022-07-27 13:35 UTC, Kasperone commented on src/views/HomeView.vue
> +  <order-preview />
ogarnięte

2022-07-27 13:36 UTC, Kasperone commented on src/views/HomeView.vue
> +<script setup>
ok ok

2022-07-27 13:36 UTC, Kasperone commented on src/components/OrderPreview.vue
>        <input class="w-[270px] h-[59px] mr-[26px] bg-gray-300" type="text" />
ok

2022-07-27 13:36 UTC, Kasperone commented on src/components/TitleComponent.vue
> +  computed: {
wchodzę w temat i ogarniam

2022-07-27 13:37 UTC, Kasperone commented on src/components/TitleComponent.vue
> +      required: false,
ok

2022-07-27 13:39 UTC, Kasperone commented on src/views/HomeView.vue
> +  name: "HomeView",
zmienione

2022-07-27 13:39 UTC, Kasperone commented on src/views/HomeView.vue
> +  <order-preview />
poprawione

2022-07-28 08:54 UTC, Sigwar commented on src/components/ActionButton.component.vue
> +    const { type } = toRefs(props);
za co odpowiada toRefs w tym przypadku?

2022-07-28 08:55 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +    class='px-11 w-[32rem] h-[48.25rem] bg-brand-blue-1 rounded-[0.625rem]'>
class do linijki gdzie jest tak section

2022-07-28 08:55 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +        id='codeInput'
id to linijki gdzie jest tag input, enter przed tagiem input

2022-07-28 08:57 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +      <label for='codeInput'>
Wyobraź sobie sytuację gdzie korzystać z kilku inputów (jakiś form). Czy dobrą praktyką jest posiadanie kilku inputów które mają id codeInput?

2022-07-28 08:57 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +        type='text' />
Tag input zawiera kilka atrybutów więc po zamknięciu tagu Enter, dla lepszej czytelności kodu

2022-07-28 08:58 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +      <c-action-button text='Apply' />
dla lepszej czytelności enter po zamknięciu tagu label, ma on kilka linijek kodu więc zasada jest taka że jeżeli zamykamy jakiś tag który jest dłuższy niż kilka linijek to enter po zamknięciu

2022-07-28 08:58 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +      <div class='font-medium text-xl text-gray-800'>0.00 &#x20AC;</div>
nie korzystamy z tego: `&#x20AC;`

2022-07-28 08:59 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +      <div class='font-medium text-xl text-gray-800'>0.00 &#x20AC;</div>
j.w.

2022-07-28 08:59 UTC, Sigwar commented on src/components/OrderPreview.component.vue
> +  name: 'cOrderPreview',
name jest przed components

2022-07-28 08:59 UTC, Sigwar commented on src/components/Title.component.vue
> +    const { type } = toRefs(props);
Dlaczego korzystasz tutaj z toRefs?

2022-07-28 09:00 UTC, Sigwar commented on src/router/index.js
> +import vHome from '../views/vHome.vue';
vHome (plik) powinien mieć nazwę Home.view.vue

2022-07-28 09:00 UTC, Sigwar commented on src/router/index.js
> +import vHome from '../views/vHome.vue';
Zobacz sobie na przykład z cOrderPreviewi to jak go importujesz do vHome.vue pliku

2022-07-28 09:19 UTC, dudeek commented on public/index.html
> +  <title><%= htmlWebpackPlugin.options.title %></title>
tu na pewno coś takiego ma być?

2022-07-28 09:27 UTC, dudeek commented on src/components/ActionButton.component.vue
> +
widzę, że niżej masz zapisane klasy i do width ustawiasz pixele, zmień jak w pozostałych widokach z px na rem.
Używaj już zawsze rem, duzo pomaga z renderowaniem komponentów na widoku

2022-07-28 09:29 UTC, dudeek commented on src/router/index.js
> +    component: vHome,
tu wtedy też bedzie do zmiany

2022-07-28 12:12 UTC, Kasperone commented on src/components/OrderPreview.component.vue
> +      <label for='codeInput'>
tylko tymczasowo, już stworzyłem komponent dla inputów

2022-07-29 12:00 UTC, merged