Feature/tsw 001 navbar
Kasperone/tees_store_web_app pull request #2
Opened 2022-07-26 18:09 UTC by Viki-Bo

2022-07-26 21:36 UTC, entrop- requested changes

2022-07-26 21:36 UTC, entrop- commented on src/components/NavBar.vue
> +      <!--flex container-->
komentarze które nic nie mówią są zbędne

2022-07-26 21:36 UTC, entrop- commented on src/components/NavBar.vue
> +          <h1 class="logo">
nie używasz tej klasy nigdzie, możesz ją wywalić. normalnie tailwind tylko w klasach, chyba że chcesz coś customo ostylować w <style>

2022-07-26 21:36 UTC, entrop- commented on src/components/NavBar.vue
> +          <a href="#" class="text-brand-gray-light">Home</a>
zawsze dodawaj translacje na stringach, nigdy nie wyświetlaj bezpośrednio

2022-07-26 21:36 UTC, entrop- commented on src/components/NavBar.vue
> +            <img src="../assets/images/image2logo.png" alt="">
nie używaj relatywnych ścieżek tylko absolutne (od @)

2022-07-26 21:36 UTC, entrop- commented on src/components/NavBar.vue
> +                <img src="../assets/images/arrow.svg" alt=""></div>
alt jest pusty

2022-07-26 21:36 UTC, entrop- commented on src/components/NavBar.vue
> +    <svg width="1440" height="1" viewBox="0 0 1440 1" fill="none" xmlns="http://www.w3.org/2000/svg">
svg do osobnego pliku

2022-07-26 21:36 UTC, entrop- commented on src/views/HomeView.vue
> +import NavBar from "../components/NavBar.vue";
ścieżki absolutne

2022-07-27 06:59 UTC, Sigwar commented on src/components/NavBar.vue
> +        <div>
Ten tag jest zbędny

2022-07-27 07:01 UTC, Sigwar commented on src/components/NavBar.vue
> +          <a href="#" class="text-brand-gray-light">Home</a>
Jeżeli tag zawiera więcej niż jeden atrybut to każdy nastepny atrybut do nowej linii. Jeżeli tag zawiera co najmniej dwa atrybuty to dajemu enter dla lepszej czytleności

2022-07-27 07:01 UTC, Sigwar commented on src/components/NavBar.vue
> +        <div class="flex flex-row space-x-14">
Enter przez nową "sekcją"

2022-07-27 07:01 UTC, Sigwar commented on src/components/NavBar.vue
> +    <svg width="1440" height="1" viewBox="0 0 1440 1" fill="none" xmlns="http://www.w3.org/2000/svg">
Atrybuty do nowej linijki

2022-07-27 07:02 UTC, Sigwar commented on src/components/NavBar.vue
> +  name: "NavBar",
Jeżeli jest to komponent to nazwij go cNavBar, jeżeli jest to widok to nazwij vNavBar.

2022-07-27 07:02 UTC, Sigwar commented on src/views/HomeView.vue
> +  <nav-bar />
Nazwa komponentu powinna być <c-nav-bar /> lub jeżeli to widok to <v-nav-bar />

2022-07-27 07:14 UTC, Viki-Bo commented on src/components/NavBar.vue
> +          <a href="#" class="text-brand-gray-light">Home</a>
Hej :) 
translacje na stringach-musze poczytać czym to jest, na ten moment nie zrozumiałam co muszę poprawić

2022-07-27 07:50 UTC, Viki-Bo commented on src/components/NavBar.vue
> +                <img src="../assets/images/arrow.svg" alt=""></div>
alt naprawiony, eslintera musimy skonfigurować, na ten moment nie miałam jeszcze.

2022-07-27 08:14 UTC, entrop- commented on src/components/NavBar.vue
> +          <a href="#" class="text-brand-gray-light">Home</a>
zapytajcie Rafała :) chodzi o i18n

2022-07-29 06:56 UTC, Sigwar commented on src/components/NavBarAccountDropDown.component.vue
> +            class="flex items-center justify-between space-x-2 px-6 text-brand-gray-light">
Enter, dla lepszej czytelnosci kodu

2022-07-29 06:56 UTC, Sigwar commented on src/components/NavBarAccountDropDown.component.vue
> +            :alt="imgAlt" />
wyrównaj alt do src i enter dla lepszej czytelności kodu

2022-07-29 06:57 UTC, Sigwar commented on src/components/NavBarAccountDropDown.component.vue
> +        <div class="flex flex-row space-x-2">
Enter przed divem

2022-07-29 06:57 UTC, Sigwar commented on src/components/NavBarAccountDropDown.component.vue
> +            <div class="text-lg">3</div>
Enter i wyrównaj atrybuty

2022-07-29 06:57 UTC, Sigwar commented on src/components/NavBarItems.component.vue
> +          <img :src="require(`@/assets/images/${imgFileName}`)"
Enter przed img

2022-07-29 06:58 UTC, Sigwar commented on src/components/NavBarItems.component.vue
> +    <c-nav-bar-account-drop-down :is-active='true'
Enter przed c-nav-bar-account-drop-down (zbyt fikuśna nazwa)

2022-07-29 06:58 UTC, Sigwar commented on src/components/NavBarItems.component.vue
> +    <c-nav-bar-account-drop-down :is-active='true'
Nie wiadomo czy to jest nav-bar, czy account czy jakiś drop down. Wszystkiego po troche

2022-07-29 06:59 UTC, Sigwar commented on src/components/NavBarLinks.component.vue
> +        <a href="#"
Zadbaj o formowanie kodu

2022-07-29 06:59 UTC, Sigwar commented on src/i18n/pl.json
> +    "next-btn":"Dalej",
nie piszemy next-btn, wystarczy samo 'next':'dalej'

2022-07-29 07:28 UTC, Viki-Bo commented on src/components/NavBarAccountDropDown.component.vue
> +            class="flex items-center justify-between space-x-2 px-6 text-brand-gray-light">
poprawione)

2022-07-29 07:28 UTC, Viki-Bo commented on src/components/NavBarAccountDropDown.component.vue
> +            :alt="imgAlt" />
done

2022-07-29 07:29 UTC, Viki-Bo commented on src/components/NavBarAccountDropDown.component.vue
> +        <div class="flex flex-row space-x-2">
done

2022-07-29 07:30 UTC, Viki-Bo commented on src/components/NavBarAccountDropDown.component.vue
> +            <div class="text-lg">3</div>
done)

2022-07-29 07:38 UTC, Viki-Bo commented on src/components/NavBarItems.component.vue
> +    <c-nav-bar-account-drop-down :is-active='true'
Jasne, już poprawione.

2022-07-29 07:41 UTC, Viki-Bo commented on src/i18n/pl.json
> +    "next-btn":"Dalej",
poprawione

2022-07-29 09:21 UTC, AdamKokoszka commented on src/components/NavBar.component.vue
> +        alt="horisontal line" />
mozna wyrownac atrybuty do jednej lini.Nie wiem czy na githubie jest przesuniecie czy u Ciebie w kodzie tez, jesli masz rowno to git

2022-07-29 12:44 UTC, Viki-Bo commented on src/components/NavBarLinks.component.vue
> +        <a href="#"
jest))

2022-07-29 12:45 UTC, Viki-Bo commented on src/components/NavBarItems.component.vue
> +          <img :src="require(`@/assets/images/${imgFileName}`)"
jest))

2022-08-01 10:44 UTC, merged

2022-08-01 13:53 UTC, AdamKokoszka commented on src/components/NavBar.component.vue
> +    <img  src="@/assets/images/line.svg"
jedna spacja po img do wywalenia

2022-08-01 13:54 UTC, AdamKokoszka commented on src/components/NavBarItemDrop.component.vue
> +        <div  v-if="isActive"
tu i ponizej w img masz podwójne spacje. Jedna wystarczy ;p

2022-08-01 13:54 UTC, AdamKokoszka commented on src/components/NavBarLinks.component.vue
> +        <a  href="#"
tu tak samo te spacje o jedna mniej