Feature/tsw 008 axios vuex
Kasperone/tees_store_web_app pull request #8
Opened 2022-08-02 07:28 UTC by Viki-Bo

2022-08-02 07:55 UTC, dudeek commented on src/components/Image.component.vue
> +  /* setup() {
masz tu komentarze

2022-08-02 07:57 UTC, dudeek commented on src/components/steps/components/AccountItems.component.vue
> +  <div>
w całym pliku atrybuty są dodawane raz w drugiej linijce, raz w pierwszej, do zmiany na pierwszą

2022-08-02 08:01 UTC, dudeek commented on src/components/steps/components/AccountItems.component.vue
>  </template>
w pliku jest zmienna która do computed wrzuca propsa po to zeby sprawdzić jego długośc. Dla mnie to jest troche bez sensu, wrzuciłbym od razu `itemArray.length` do template

2022-08-02 08:02 UTC, dudeek commented on src/components/steps/components/AccountItems.component.vue
>  </template>
+ ten dodany tutyaj div jest an tym samym poziomie co ten zaraz nad nim

2022-08-02 08:04 UTC, dudeek commented on src/store/index.js
> +      console.log(image);
nioe usunęłaś console loga

2022-08-02 08:08 UTC, AdamKokoszka commented on src/components/Image.component.vue
> +      return this.$store.state.image;
to jest napisanie w option api a wczesniej pisaliscie w composition api i chyba tego nalezy sie trzymac

2022-08-02 08:10 UTC, AdamKokoszka commented on src/components/steps/components/AccountItems.component.vue
>      v-for="(item, index) in itemArray"
pierwszy atrubut (v-for) zapisujemy w jednej lini z tagiem (div)

2022-08-02 09:37 UTC, Viki-Bo commented on src/components/steps/components/AccountItems.component.vue
>      v-for="(item, index) in itemArray"
poprawione

2022-08-02 09:42 UTC, Viki-Bo commented on src/components/steps/components/AccountItems.component.vue
> +  <div>
poprawione

2022-08-02 10:36 UTC, Viki-Bo commented on src/components/steps/components/AccountItems.component.vue
>  </template>
poprawione

2022-08-03 14:14 UTC, AdamKokoszka commented on src/components/steps/components/AccountItems.component.vue
> +              src="@/assets/images/Line.png"
spacja wiecej

2022-08-03 14:35 UTC, entrop- requested changes

2022-08-03 14:35 UTC, entrop- commented on src/components/steps/components/AccountItems.component.vue
> +      <li :class="[currentPage === item.PageName ? 'text-color' : '']"
możesz to też zapisać w postaci obiektu ` {'text-color': currentPage === item.PageName} `, wtedy nie będziesz musiała pustego `''` wstawiać

2022-08-03 14:35 UTC, entrop- commented on src/components/steps/components/AccountItems.component.vue
> +      <li :class="[index === itemArray.length - 1 ? 'hidden' : '']"
jw, generalnie jesli to ma być prosty wynik true/false to obiekt, jesli jest jakaś alternatywa że potrzeba innych klas dla prawdy i innych dla fałszu to wtedy dopiero tablica

2022-08-03 14:35 UTC, entrop- commented on src/store/index.js
> +            url = `https://picsum.photos/id/${items[0].id}/400/200/?blur=${payload}`;
jak trawersujesz obiekty to dla bezpeiczeństwa polecam optional chaining `items[0]?.id` bo to nigdy nie wiesz czy na pewno będzie ta wartość w obiekcie/tablicy

2022-08-04 08:27 UTC, Viki-Bo commented on src/components/steps/components/AccountItems.component.vue
> +      <li :class="[currentPage === item.PageName ? 'text-color' : '']"
Na innym brachu jest poprawione.

2022-08-08 11:24 UTC, AdamKokoszka commented on src/components/Image.component.vue
> +    alt="print image"
wczesniej bylo poprawnie. Pierwszy atrybut powinien byc na równi z img

2022-08-08 11:25 UTC, AdamKokoszka commented on src/components/ImageSettings.component.vue
> +        <c-title
tu i ponizej kazdy pierwszy atrybut powinien byc na rowni z tagiem.

2022-08-08 11:25 UTC, AdamKokoszka commented on src/components/ImageSettings.component.vue
> +      <c-action-button text="Wstecz" />
Wstecz i dalej do i18n

2022-08-08 11:27 UTC, AdamKokoszka commented on src/components/ImageSettings.component.vue
> +      console.log('myParams:', myParams);
console log do wywalenia

2022-08-08 11:27 UTC, AdamKokoszka commented on src/components/InputRange.component.vue
> +        @change="$emit('valueChanged', inputValue)"
tu i wyzej, podobnie jak wczesniej. Pierwszy atrybut na rowni z tagiem

2022-08-08 11:28 UTC, AdamKokoszka commented on src/components/RadioButton.component.vue
> +    <input
j.w.

2022-08-08 11:28 UTC, AdamKokoszka commented on src/components/RadioButton.component.vue
> +      <label
j.w.

2022-08-08 11:28 UTC, AdamKokoszka commented on src/components/NavBar.component.vue
> +    <img
j.w.

2022-08-08 11:28 UTC, AdamKokoszka commented on src/components/steps/components/AccountItems.component.vue
> +  <div
j.w.

2022-08-08 11:28 UTC, AdamKokoszka commented on src/components/steps/components/AccountItems.component.vue
> +        :class="[currentPage === item.PageName ? 'text-color' : '']"
j.w. ;p

2022-08-08 11:29 UTC, AdamKokoszka commented on src/store/index.js
> +        // alert('Zle');
komentarz out chyba ze ma alert zostac to odkomentowac

2022-08-08 21:31 UTC, dudeek commented on src/components/ImageSettings.component.vue
> +          text="Ustawienia zdjęcia" />
jeżeli podpinacie tłumaczenia to też wrzucałbym je w to miejsce

2022-08-08 21:31 UTC, dudeek commented on src/components/ImageSettings.component.vue
> +      <c-action-button text="Dalej" />
tu tez

2022-08-08 21:34 UTC, dudeek commented on src/components/RadioButton.component.vue
> +        :for="radioBtnGray"
2x atrybut :for? coś jest nie tak

2022-08-08 21:35 UTC, dudeek commented on src/components/RadioButton.component.vue
> -      <label :for="radioBtnValue"
po co tak ogolnie label jest wrzuoony do spana? span jest niepotrzbny. Tak ogolnie też zapisałbym input wewnątrz labela. Wtedy mozna pozbyć się atrybutu id z inputa i for z labela

2022-08-08 21:36 UTC, dudeek commented on src/components/RadioButton.component.vue
> +      default: 'No',
jakie zadanie mają te stringi? Do togglowania dwóch stanów czyli Yes/No zastosowałbym Boolean, chyba ze to przyjmuje jeszcze jakas trzecią wartość, ale nie wydaje mi sie w tym przypadku

2022-08-08 21:37 UTC, dudeek commented on src/store/index.js
> +        // alert('Zle');
do wyrzucenia

2022-08-09 08:00 UTC, merged